# Copyright (c) 2015 Ken Wu
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
# -----------------------------------------------------------------------------
#
# Author: Ken Wu
# Date: Apr 2015
# URL: https://github.com/wwken

# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
NUM_BOXES = 3 #4 # first is master
CLUSTER_PREFIX = "hadoop"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.puppet_install.puppet_version = "3.7.4"

  (0...NUM_BOXES).each do |num|
      if num > 0
        nodename = "#{CLUSTER_PREFIX}-node%03d" % num
      else
        nodename = "#{CLUSTER_PREFIX}-master"
      end
      config.vm.define nodename.to_sym do |node|
        node.vm.box = "precise64"
        node.vm.box_url = "http://files.vagrantup.com/precise64.box"
        node.hostmanager.enabled = false
        ip_num=num+11
        node.vm.network "private_network", ip: "192.168.109.#{ip_num}"
        node.vm.hostname = "#{nodename}"
        node.vm.provider "virtualbox" do |v|
          v.name = "#{nodename}"
          v.customize [
             "modifyvm", :id, 
             "--memory", 1024
          ]
        end
        
        # Enable shell provisioning to bootstrap puppet
        node.vm.provision :shell, :path => "bootstrap.sh"
        
        node.vm.provision :shell do |sh|
          sh.inline = "echo '#{nodename}' > /etc/hostname
          hostname `cat /etc/hostname`"
        end

        node.vm.provision :shell, :inline => "apt-get update"
        node.vm.provision :hostmanager
        node.vm.provision :puppet, :options => ['--verbose', '--debug'] do |puppet|
          puppet.facter = {'CLUSTER_PREFIX' => '#{CLUSTER_PREFIX}'}
          puppet.manifests_path = "puppet/manifests"
          puppet.module_path = "puppet/modules"
          puppet.manifest_file  = "init.pp"
          #puppet.options = "--verbose --debug --hiera_config /vagrant/puppet/hiera.yaml"
        end
      end #end nodename.to_sym
  end #end the for loop each server
end #end vagrant config
